name: Release Github
on:
  workflow_dispatch:
    branches: [ main ]
  # workflow_run:
  #   branches: [ main ]
  #   workflows: ["Release Npm"]
  #   types:
  #     - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@ekarpovs'
      - run: npm ci
      # - run: npm unpublish --force
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
